### ISSUE TITLE
need help to make peacock

### ISSUE THREAD

**Issue by Dhravya** [prvnsmpth/place-india-flag#1]
This website could be REALLY useful for making the peacock. We also have some more ideas like taj mahal which would be done. 
Here's a detailed graph of places
![image](https://user-images.githubusercontent.com/63950637/161381414-2230ea84-2579-4ebb-a9d3-71dce28cc32a.png)

Can you please help us? Join the indianplace discord server and ping me @Spacedoggo https://discord.gg/53PXD9SV

**Comment by prvnsmpth** [comment]
Okay, let me see if I can make the peacock version of this, should be easy enough to do.

**Comment by Dhravya** [comment]
Thanks a lot man! Let me know if I can help

**Comment by Dhravya** [comment]
![image](https://user-images.githubusercontent.com/63950637/161382108-def36368-1075-4b13-aabd-c85549be0833.png)
Here's a diagram for taj mahal

**Comment by prvnsmpth** [comment]
Peacock is live at: https://place-india-flag.vercel.app/peacock

**Comment by prvnsmpth** [comment]
There is a map generator at https://place-india-flag.vercel.app/generate.

But drawing out this Taj Mahal will be super tedious.

**Comment by Dhravya** [comment]
Damn thanks a lot. I understand about the Taj mahal. Do you draw it manually? Damn

Maybe if we can provide a JSON file in format of (x, y, color), you could map through the entire thing ? 

I could make that json using Python openCV, but idk nextJS well enough yet

**Comment by Dhravya** [comment]
Hey there, could you please join our discord, the managers want to honor you for your help in making the peacock
https://discord.gg/53PXD9SV
Ping me @Spacedoggo#0001 after joining
